// src/web/shared/layout/Sidebar.tsx
import React, { useState, useEffect, type FC } from "react";
import { NavLink } from "react-router-dom";
import {
  LayoutDashboard,
  Kanban,
  Bot,
  Workflow,
  Users2,
  FolderGit2,
  Cpu,
  Layers,
  Boxes,
  History,
  Bell,
  Settings,
  KeyRound,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  Shield,
  Activity,
  X,
} from "lucide-react";
import { useOpenCorp } from "../../providers/OpenCorpProvider.js";

interface ItemNav {
  to: string;
  rotulo: string;
  icone: React.ComponentType<{ size?: number; className?: string }>;
  badge?: string;
  badgeCor?: string;
}

interface GrupoNav {
  titulo: string;
  itens: ItemNav[];
}

const GRUPOS_NAV: GrupoNav[] = [
  {
    titulo: "OPERACIONAL",
    itens: [
      { to: "/home", rotulo: "Home Dashboard", icone: LayoutDashboard },
      { to: "/tasks", rotulo: "Tarefas & Kanban", icone: Kanban },
      { to: "/secretario", rotulo: "Secretário Executivo", icone: Bot, badge: "IA", badgeCor: "bg-emerald-950 border-emerald-800 text-emerald-400" },
      { to: "/fluxos", rotulo: "Fluxos de Automação", icone: Workflow },
      { to: "/reunioes", rotulo: "Reuniões & Deliberações", icone: Users2 },
    ],
  },
  {
    titulo: "DESENVOLVIMENTO",
    itens: [
      { to: "/workspace", rotulo: "Workspace IDE", icone: FolderGit2 },
      { to: "/agentes", rotulo: "Agentes & Teams", icone: Cpu },
      { to: "/apps", rotulo: "Apps & MCPs", icone: Layers },
      { to: "/ativos", rotulo: "Ativos & Skills", icone: Boxes },
    ],
  },
  {
    titulo: "GOVERNANÇA & SRE",
    itens: [
      { to: "/historico", rotulo: "Histórico de Auditoria", icone: History },
      { to: "/notificacoes", rotulo: "Notificações", icone: Bell },
      { to: "/config", rotulo: "Configurações", icone: Settings },
      { to: "/secrets", rotulo: "Segredos & Chaves", icone: KeyRound },
      { to: "/docs", rotulo: "Documentação", icone: BookOpen },
    ],
  },
];

export interface SidebarProps {
  mobileAberta: boolean;
  aoFecharMobile: () => void;
}

export const Sidebar: FC<SidebarProps> = ({ mobileAberta, aoFecharMobile }) => {
  const { workspaceId } = useOpenCorp();
  const [recolhida, setRecolhida] = useState<boolean>(() => {
    return typeof window !== "undefined" && localStorage.getItem("oc_sidebar_collapsed") === "1";
  });

  const alternarRecolhida = () => {
    setRecolhida((prev) => {
      const proximo = !prev;
      if (typeof window !== "undefined") {
        localStorage.setItem("oc_sidebar_collapsed", proximo ? "1" : "0");
      }
      return proximo;
    });
  };

  return (
    <>
      {mobileAberta && (
        <div
          className="fixed inset-0 z-40 bg-black/70 backdrop-blur-xs md:hidden"
          onClick={aoFecharMobile}
          aria-hidden="true"
        />
      )}

      <aside
        className={`fixed inset-y-0 left-0 z-50 flex w-72 shrink-0 flex-col bg-zinc-950 border-r border-zinc-850 select-none transition-[transform,width] duration-300 md:relative md:z-30 md:translate-x-0 ${
          mobileAberta ? "translate-x-0" : "-translate-x-full"
        } ${recolhida ? "md:w-16" : "md:w-60"}`}
      >
        {/* Topo com Logo e Versão */}
        <div className="flex items-center justify-between h-14 px-3.5 border-b border-zinc-850/80 bg-zinc-950/80">
          <div className="flex items-center gap-2.5 overflow-hidden">
            <div className="h-8 w-8 rounded-xl bg-emerald-600 flex items-center justify-center text-white shadow-md shadow-emerald-950/60 shrink-0">
              <Shield size={18} />
            </div>
            <div className={`flex flex-col min-w-0 ${recolhida ? "md:hidden" : ""}`}>
              <span className="font-bold text-sm tracking-tight text-zinc-100 flex items-center gap-1.5">
                OpenCorp
                <span className="text-[10px] font-mono px-1 py-0.2 rounded bg-emerald-950/60 border border-emerald-800/40 text-emerald-400">
                  v0.7
                </span>
              </span>
              <span className="text-[11px] text-zinc-500 truncate">Empresa Autônoma</span>
            </div>
          </div>

          <button
            type="button"
            onClick={aoFecharMobile}
            className="md:hidden p-2 -mr-2 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-900 transition-colors cursor-pointer"
            aria-label="Fechar menu de navegação"
            title="Fechar menu de navegação"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

      {/* Navegação por Grupos */}
      <nav className="flex-1 overflow-y-auto px-2 py-3 space-y-4 scrollbar-thin">
        {GRUPOS_NAV.map((grupo) => (
          <div key={grupo.titulo} className="space-y-1">
            <span
              className={`px-3 text-[10px] font-bold text-zinc-400 tracking-wider uppercase block ${
                recolhida ? "md:hidden" : ""
              }`}
            >
              {grupo.titulo}
            </span>

            <div className="space-y-0.5">
              {grupo.itens.map((item) => {
                const Icone = item.icone;

                return (
                  <NavLink
                    key={item.to}
                    to={item.to}
                    onClick={aoFecharMobile}
                    className={({ isActive }) =>
                      `flex items-center gap-2.5 px-3 py-1.5 rounded-xl text-xs font-medium transition-all group relative ${
                        isActive
                          ? "bg-emerald-500/10 text-emerald-400 border-r-2 border-emerald-500 font-semibold"
                          : "text-zinc-400 hover:text-zinc-100 hover:bg-zinc-900/60"
                      } ${recolhida ? "md:justify-center md:px-0 md:py-2" : ""}`
                    }
                    title={recolhida ? item.rotulo : undefined}
                  >
                    <Icone size={16} className="shrink-0" />

                    <span className={`truncate flex-1 ${recolhida ? "md:hidden" : ""}`}>
                      {item.rotulo}
                    </span>

                    {item.badge && (
                      <span
                        className={`text-[9px] font-mono px-1.5 py-0.2 rounded-full border font-bold ${
                          recolhida ? "md:hidden " : ""
                        }${
                          item.badgeCor || "bg-zinc-800 border-zinc-700 text-zinc-300"
                        }`}
                      >
                        {item.badge}
                      </span>
                    )}
                  </NavLink>
                );
              })}
            </div>
          </div>
        ))}
      </nav>

      {/* Footer com Toggle de Recolhimento e Status do Daemon */}
      <div className="p-2.5 border-t border-zinc-850/80 bg-zinc-950 space-y-2">
        <button
          type="button"
          onClick={alternarRecolhida}
          className="hidden md:flex w-full items-center justify-center gap-2 py-1.5 rounded-xl bg-zinc-900/60 hover:bg-zinc-850 text-zinc-400 hover:text-zinc-200 text-xs transition-colors cursor-pointer border border-zinc-850"
          title={recolhida ? "Expandir menu lateral" : "Recolher menu lateral"}
        >
          {recolhida ? (
            <ChevronRight size={15} />
          ) : (
            <>
              <ChevronLeft size={15} />
              <span>Recolher Menu</span>
            </>
          )}
        </button>

        <div
          className={`items-center justify-between px-2 text-[11px] text-zinc-500 font-mono ${
            recolhida ? "flex md:hidden" : "flex"
          }`}
        >
          <div className="flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
            <span>{workspaceId || "daemon"}</span>
          </div>
          <Activity size={12} className="text-zinc-600" />
        </div>
        {recolhida && (
          <div className="hidden md:flex justify-center" title={`Workspace: ${workspaceId}`}>
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
          </div>
        )}
      </div>
      </aside>
    </>
  );
};

// src/web/components/Sidebar.tsx
import { type Component, createSignal, For, Show } from "solid-js";
import { A, useLocation } from "@solidjs/router";
import {
  Home,
  MessageSquare,
  FolderCode,
  CheckSquare,
  Bot,
  Users,
  Calendar,
  GitBranch,
  Webhook,
  KeyRound,
  History,
  Settings,
  ChevronLeft,
  ChevronRight,
  Building2,
  ChevronsUpDown,
  BookOpen,
  Plus,
  X,
} from "lucide-solid";
import { wsAtivo, setWsAtivo, workspaces, sidebarMobileAberta, setSidebarMobileAberta } from "../lib/context";
import { NovoWorkspaceModal } from "./NovoWorkspaceModal";

interface NavItem {
  href: string;
  label: string;
  icone: any;
  badge?: () => number | undefined;
  badgeTag?: string;
}

interface NavGroup {
  titulo: string;
  itens: NavItem[];
}

export const Sidebar: Component = () => {
  const location = useLocation();
  const [colapsado, setColapsado] = createSignal(localStorage.getItem("oc-sidebar-colapsada") === "1");
  const [modalNovoWs, setModalNovoWs] = createSignal(false);

  const toggleColapso = () => {
    const novo = !colapsado();
    setColapsado(novo);
    localStorage.setItem("oc-sidebar-colapsada", novo ? "1" : "0");
  };

  const navGroups: NavGroup[] = [
    {
      titulo: "Operação",
      itens: [
        { href: "/home", label: "Início", icone: Home },
        { href: "/secretario", label: "Secretário", icone: MessageSquare },
        { href: "/workspace", label: "Workspace", icone: FolderCode },
        { href: "/tasks", label: "Tasks", icone: CheckSquare },
        { href: "/agentes", label: "Agentes", icone: Bot },
      ],
    },
    {
      titulo: "Automação",
      itens: [
        { href: "/agenda", label: "Agenda", icone: Calendar },
        { href: "/fluxos", label: "Fluxos", icone: GitBranch, badgeTag: "Alfa" },
        { href: "/hooks", label: "Hooks", icone: Webhook, badgeTag: "Alfa" },
      ],
    },
  ];

  // Itens fixos na base da sidebar (apenas ícones: Apps&Secrets, Histórico, Documentação, Configurações)
  const itensFixosInferiores = [
    { href: "/apps", label: "Apps & Secrets", icone: KeyRound },
    { href: "/historico", label: "Histórico", icone: History },
    { href: "/docs", label: "Documentação", icone: BookOpen },
    { href: "/config", label: "Configurações", icone: Settings },
  ];

  const isAtivo = (href: string) => {
    if (href === "/home") return location.pathname === "/" || location.pathname === "/home";
    return location.pathname.startsWith(href);
  };

  return (
    <>
      {/* Backdrop mobile */}
      <Show when={sidebarMobileAberta()}>
        <div
          class="fixed inset-0 bg-black/60 backdrop-blur-xs z-40 md:hidden animate-in fade-in duration-150"
          onClick={() => setSidebarMobileAberta(false)}
        />
      </Show>

      <aside
        class={`flex flex-col bg-zinc-950 border-r border-zinc-800/80 transition-all duration-200 select-none z-50 h-full ${
          sidebarMobileAberta()
            ? "fixed inset-y-0 left-0 w-72 shadow-2xl md:static md:shadow-none md:flex"
            : "hidden md:flex flex-shrink-0"
        } ${colapsado() ? "md:w-16" : "md:w-60"}`}
      >
        {/* Cabeçalho do App / Logo */}
        <div class="h-14 flex items-center justify-between px-3 border-b border-zinc-800/80">
          <div class="flex items-center gap-2.5 overflow-hidden">
            <div class="h-8 w-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 flex-shrink-0 font-mono font-bold text-xs shadow-xs">
              OC
            </div>
            <Show when={!colapsado() || sidebarMobileAberta()}>
              <div class="flex flex-col min-w-0">
                <span class="font-bold tracking-tight text-sm text-zinc-100 truncate">opencorp</span>
                <span class="text-[9px] text-zinc-500 font-mono">v0.7.0</span>
              </div>
            </Show>
          </div>
          <div class="flex items-center gap-1">
            {/* Botão fechar drawer no mobile */}
            <button
              type="button"
              onClick={() => setSidebarMobileAberta(false)}
              class="md:hidden p-1.5 rounded-lg text-zinc-400 hover:text-zinc-100 hover:bg-zinc-850 transition-colors"
              title="Fechar menu"
            >
              <X size={16} />
            </button>
            {/* Botão colapsar no desktop */}
            <button
              type="button"
              onClick={toggleColapso}
              class="hidden md:flex !bg-transparent hover:!bg-zinc-900/80 p-1.5 rounded-lg text-zinc-400 hover:text-zinc-100 border border-transparent hover:border-zinc-800 transition-all cursor-pointer"
              title={colapsado() ? "Expandir menu" : "Recolher menu"}
            >
              <Show when={colapsado()} fallback={<ChevronLeft size={16} />}>
                <ChevronRight size={16} />
              </Show>
            </button>
          </div>
        </div>

      {/* Workspace Ativo Selector */}
      <div class="px-3 py-2.5 border-b border-zinc-800/60">
        <Show
          when={!colapsado()}
          fallback={
            <div
              class="h-8 w-full rounded-md bg-zinc-900/80 border border-zinc-800/80 flex items-center justify-center text-zinc-300"
              title={`Workspace: ${wsAtivo()}`}
            >
              <Building2 size={14} />
            </div>
          }
        >
          <div class="flex items-center gap-1.5">
            <div class="relative flex-1 flex items-center bg-zinc-900/80 border border-zinc-800 rounded-lg px-2.5 py-1.5 focus-within:border-zinc-700 min-w-0">
              <Building2 size={13} class="text-emerald-400 flex-shrink-0 mr-2" />
              <select
                class="w-full bg-transparent text-xs font-medium text-zinc-200 focus:outline-none cursor-pointer appearance-none truncate pr-4"
                value={wsAtivo()}
                onChange={(e) => setWsAtivo(e.currentTarget.value)}
              >
                <option value="" class="bg-zinc-900 text-zinc-400" selected={!wsAtivo()}>
                  {workspaces().length === 0 ? "(Nenhuma empresa)" : "(Início / Sem empresa)"}
                </option>
                <For each={workspaces()}>
                  {(w) => (
                    <option value={w.id} class="bg-zinc-900 text-zinc-200" selected={w.id === wsAtivo()}>
                      {w.id}
                    </option>
                  )}
                </For>
              </select>
              <ChevronsUpDown size={12} class="text-zinc-500 absolute right-2 pointer-events-none" />
            </div>
            <button
              type="button"
              onClick={() => setModalNovoWs(true)}
              class="!bg-zinc-900/80 hover:!bg-zinc-800 p-1.5 rounded-lg text-zinc-400 hover:text-emerald-400 border border-zinc-800 transition-all cursor-pointer flex-shrink-0"
              title="Novo Workspace ou Conectar Pasta"
            >
              <Plus size={14} />
            </button>
          </div>
        </Show>
      </div>

      <NovoWorkspaceModal open={modalNovoWs()} onClose={() => setModalNovoWs(false)} />

      {/* Lista de Navegação */}
      <nav class="flex-1 overflow-y-auto py-3 px-2.5 space-y-4 scrollbar-thin">
        <For each={navGroups}>
          {(grupo) => (
            <div class="space-y-1">
              <Show when={!colapsado()}>
                <div class="px-2 pb-1 text-[10px] font-semibold tracking-wider uppercase text-zinc-500">
                  {grupo.titulo}
                </div>
              </Show>

              <For each={grupo.itens}>
                {(item) => {
                  const Icone = item.icone;
                  const ativo = () => isAtivo(item.href);

                  return (
                    <A
                      href={item.href}
                      onClick={() => setSidebarMobileAberta(false)}
                      class={`flex items-center gap-2.5 px-2.5 py-2 rounded-lg text-xs font-medium transition-all ${
                        ativo()
                          ? "bg-zinc-900 text-zinc-100 font-semibold border border-zinc-800/90 shadow-xs"
                          : "text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/40"
                      } ${colapsado() ? "justify-center px-0" : ""}`}
                      title={colapsado() ? (item.badgeTag ? `${item.label} (${item.badgeTag})` : item.label) : undefined}
                    >
                      <div class="relative flex items-center justify-center">
                        <Icone
                          size={16}
                          class={`flex-shrink-0 ${
                            ativo() ? "text-emerald-400" : "text-zinc-400"
                          }`}
                        />
                        <Show when={colapsado() && item.badgeTag}>
                          <span
                            class="absolute -top-1.5 -right-2 px-0.5 min-w-[11px] h-2.5 rounded-full text-[7px] font-bold font-mono bg-amber-500/20 text-amber-400 border border-amber-500/30 flex items-center justify-center leading-none"
                            title={item.badgeTag}
                          >
                            α
                          </span>
                        </Show>
                      </div>

                      <Show when={!colapsado()}>
                        <span class="truncate flex-1">{item.label}</span>
                        <Show when={item.badgeTag}>
                          <span class="px-1.5 py-0.5 rounded text-[9px] font-semibold tracking-wider uppercase font-mono bg-amber-500/15 text-amber-400 border border-amber-500/30 leading-none">
                            {item.badgeTag}
                          </span>
                        </Show>
                        <Show when={item.badge && item.badge()! > 0}>
                          <span class="px-1.5 py-0.2 rounded-full text-[10px] font-mono bg-amber-500/20 text-amber-400 border border-amber-500/30">
                            {item.badge!()}
                          </span>
                        </Show>
                      </Show>
                    </A>
                  );
                }}
              </For>
            </div>
          )}
        </For>
      </nav>

      {/* Dock Fixo Inferior — Apenas Ícones: Apps&Secrets, Histórico, Docs, Configurações */}
      <div class="border-t border-zinc-800/80 bg-zinc-950/95 p-2 flex-shrink-0">
        <div
          class={
            colapsado()
              ? "grid grid-cols-2 gap-1.5 justify-items-center"
              : "flex items-center justify-between px-1"
          }
        >
          <For each={itensFixosInferiores}>
            {(item) => {
              const Icone = item.icone;
              const ativo = () => isAtivo(item.href);

              return (
                <A
                  href={item.href}
                  onClick={() => setSidebarMobileAberta(false)}
                  class={`relative p-2 rounded-xl transition-all flex items-center justify-center group ${
                    ativo()
                      ? "bg-zinc-900 text-emerald-400 border border-zinc-750 shadow-xs"
                      : "text-zinc-400 hover:text-zinc-100 hover:bg-zinc-900/70 border border-transparent hover:border-zinc-800/80"
                  }`}
                  title={item.label}
                >
                  <Icone
                    size={17}
                    class={`transition-colors ${
                      ativo() ? "text-emerald-400" : "text-zinc-400 group-hover:text-zinc-200"
                    }`}
                  />

                  {/* Tooltip flutuante superior no hover */}
                  <div class="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 px-2.5 py-1 bg-zinc-900 border border-zinc-700/80 text-[11px] text-zinc-200 font-medium rounded-md shadow-2xl whitespace-nowrap opacity-0 pointer-events-none group-hover:opacity-100 transition-opacity z-50">
                    {item.label}
                  </div>
                </A>
              );
            }}
          </For>
        </div>
      </div>
    </aside>
    </>
  );
};
